spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyqwsq?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名）
    #到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      id-type: auto
      logic-delete-field: delFlag #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值
  # 配置xml文件的存放目录
  mapper-locations: classpath*:/mapper/**/*.xml


